#!/bin/bash
set -e

# Ensure /app resolves to workspace root
[ -e /app ] || ln -sf "$(pwd)" /app

# Apply test files from gold patch (restored on exit)
trap "git checkout HEAD -- internal/cache/cache_test.go internal/server/middleware/grpc/middleware_test.go internal/storage/cache/cache_test.go 2>/dev/null || true" EXIT
git checkout e2bd19dafa7166c96b082fb2a59eb54b4be0d778 -- internal/cache/cache_test.go internal/server/middleware/grpc/middleware_test.go internal/storage/cache/cache_test.go

echo "=== Running tests ==="
bash <(sed 's/\r//g' .swebench/run_script.sh) TestAuditUnaryInterceptor_UpdateVariant,TestAuditUnaryInterceptor_CreateSegment,TestGetJSONHandleGetError,TestAuditUnaryInterceptor_CreateToken,TestAuditUnaryInterceptor_UpdateRollout,TestEvaluationCacheUnaryInterceptor_Evaluate,TestCacheControlUnaryInterceptor,TestAuditUnaryInterceptor_DeleteVariant,TestGetFlagCached,TestGetEvaluationRulesCached,TestAuditUnaryInterceptor_CreateDistribution,TestEvaluationUnaryInterceptor_Noop,TestEvaluationUnaryInterceptor_Evaluation,TestAuditUnaryInterceptor_UpdateRule,TestAuditUnaryInterceptor_CreateNamespace,TestGetEvaluationRules,TestAuditUnaryInterceptor_DeleteDistribution,TestValidationUnaryInterceptor,TestAuditUnaryInterceptor_DeleteNamespace,TestWithDoNotStore,TestAuditUnaryInterceptor_UpdateConstraint,TestIsDoNotStore,TestAuditUnaryInterceptor_CreateVariant,TestEvaluationCacheUnaryInterceptor_Evaluation_Variant,TestAuditUnaryInterceptor_DeleteRollout,TestEvaluationUnaryInterceptor_BatchEvaluation,TestAuditUnaryInterceptor_DeleteSegment,TestAuditUnaryInterceptor_DeleteConstraint,TestAuditUnaryInterceptor_DeleteFlag,TestAuditUnaryInterceptor_UpdateNamespace,TestAuditUnaryInterceptor_CreateRule,TestAuthMetadataAuditUnaryInterceptor,TestAuditUnaryInterceptor_UpdateFlag,TestAuditUnaryInterceptor_CreateConstraint,TestErrorUnaryInterceptor,TestEvaluationCacheUnaryInterceptor_Evaluation_Boolean,TestAuditUnaryInterceptor_UpdateSegment,TestAuditUnaryInterceptor_DeleteRule,TestGetJSONHandleUnmarshalError,TestSetJSONHandleMarshalError,TestAuditUnaryInterceptor_CreateFlag,TestAuditUnaryInterceptor_UpdateDistribution,TestAuditUnaryInterceptor_CreateRollout
